#!/usr/bin/python


"""
    Starter code for the evaluation mini-project.
    Start by copying your trained/tested POI identifier from
    that which you built in the validation mini-project.

    This is the second step toward building your POI identifier!

    Start by loading/formatting the data...
"""
import os
import joblib
import sys

from sklearn.metrics import precision_score, recall_score

sys.path.append(os.path.abspath("../tools/"))
from feature_format import featureFormat, targetFeatureSplit

data_dict = joblib.load(open("../final_project/final_project_dataset.pkl", "rb") )

### add more features to features_list!
features_list = ["poi", "salary"]

data = featureFormat(data_dict, features_list, sort_keys = '../tools/python2_lesson14_keys.pkl')
labels, features = targetFeatureSplit(data)

# Training and Testing

from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels,
                                                                            test_size=0.3, random_state=42)

# Building decision Tree Classifier
from sklearn import tree
from sklearn import metrics
from sklearn.metrics import precision_score

clf = tree.DecisionTreeClassifier()
clf.fit(features_test, labels_test)

pred_1 = clf.predict(features_test)

#print(clf.score(features_test, labels_test))


#print(features_test)
#print(len(features_test))
#print(labels_test)
#print(len(labels_test))

#print(len(features_test))
#print(len(features_train))

#print(1.0 - 5.0/29)

#print(pred_1)
#print(labels_test)

print(precision_score(labels_test, pred_1))

print(recall_score(labels_test, pred_1))
